### ISSUE TITLE
Approximate date for code relee 

### ISSUE THREAD

**Issue by ruili3** [KovenYu/WonderWorld#2]
Hey,

Thanks for your awesome work! Do you have an approximate date for code release, e.g., within the following month or after the paper is accepted by the targeted venue? 

cant wait to have a try and do some follow-ups 

thanks

**Comment by qtencent7** [comment]
什么时候能出来代码呢

**Comment by KovenYu** [comment]
I suppose next Feb. Thanks!

**Comment by halr9000** [comment]
Unstarred this garbage repo

**Comment by KovenYu** [comment]
We Just released code. Feel free to try!
