### ISSUE TITLE
Could You Provide an version that supports holographic display

### ISSUE THREAD

**Issue by Jup33Q** [KovenYu/WonderWorld#3]
Hello, I have read your paper on arxiv, and I spot that you used something like depthanything v2 capture the objects's feature (maybe with cross-attention).Great Job! And as an good and honest adivce, you can actually integrate your idea together with the holographic display like LKG. I have experienced 2 year development and test on those device, and figured out that RGB-D is the most economical way to generate VR-format medium. If necessary, I can provide my python code of an langgraph program that integrate CogView and Depthanything-hf as an reference.

**Comment by KovenYu** [comment]
Thanks for the note. I think having holographic version is very interesting (I actually seriously considered doing a research follow up on this) but at the moment our team does not have the capacity to do. Feel free to do that by yourself after we release code. Thanks.

**Comment by Jup33Q** [comment]
thanks, stay tuned
