### ISSUE TITLE
Inquiry about the code release of "WonderWorld: Interactive 3D Scene Generation from a Single Image"

### ISSUE THREAD

**Issue by Bryant-Teng** [KovenYu/WonderWorld#4]
I hope this email finds you well.  I recently read your paper titled **WonderWorld**: Interactive 3D Scene Generation from a Single Image, and I am truly impressed by your work and its potential applications.

I noticed that the code and model are not currently available. I was wondering if you have plans to release the source code and, if so, whether you could share an approximate timeline for the release. Having access to the implementation would be immensely helpful for the research community, and I am keen to explore its applications further in my own work.

Thank you for your time and for contributing such inspiring research. I look forward to your response.

Best regards,
Fei Teng

**Comment by KovenYu** [comment]
Thanks for asking. We plan to release the full code in late Jan.

**Comment by KovenYu** [comment]
We Just released code. Feel free to try!

**Comment by blakkd** [comment]
Oh my oh my, what a present oh-oh-oh
Thanks guys you rock
Can't wait to give it a spin!
