### ISSUE TITLE
Missing build_sam.py 

### ISSUE THREAD

**Issue by Bryceoz** [KovenYu/WonderWorld#6]
I needed to add `build_sam.py` to RepViT/sam/repvit_sam/build_sam.py in order to make `run.py` work

**Comment by haoyi-duan** [comment]
Thank you for pointing it out! We've uploaded it.

**Comment by supersyz** [comment]
@haoyi-duan  Hi, I also meet the same problem, and I do not find the uploaded RepViT/sam/repvit_sam/build_sam.py, do I need to wait for some time?

**Comment by haoyi-duan** [comment]
> @haoyi-duan Hi, I also meet the same problem, and I do not find the uploaded RepViT/sam/repvit_sam/build_sam.py, do I need to wait for some time?

Hi, I uploaded the file. Let me know if you have further questions!

**Comment by supersyz** [comment]
@haoyi-duan  Hi，thanks for your update， I‘ve successfully ran the project.  I notice that by press "x" ， the saved models consists of config, pictures and content logs. What else can I do if I want to visualize the saved 3D scenes offline with more details?

**Comment by Bryceoz** [comment]
awesome, looks like you can close this issue.
